name: pumba_project
description: "A new Pumba project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.5.1
  form_field_validator: ^1.1.0
  provider: ^6.1.2
  timezone: ^0.10.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
