// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-zHg7SUaeSCWocatyQ2J5Yn_JgojQo8',
    appId: '1:461278347881:web:708a2992c8ac4431e918f8',
    messagingSenderId: '461278347881',
    projectId: 'pumba-project-3b8bb',
    authDomain: 'pumba-project-3b8bb.firebaseapp.com',
    storageBucket: 'pumba-project-3b8bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkkqa1UkvhWr1STztDRd_aG0KTZoe040',
    appId: '1:461278347881:android:d464d2a72d8cfe3ae918f8',
    messagingSenderId: '461278347881',
    projectId: 'pumba-project-3b8bb',
    storageBucket: 'pumba-project-3b8bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRygzP9gMkA51Wg93rJCWb5dQnCd921Rk',
    appId: '1:461278347881:ios:1df0deefe5baed11e918f8',
    messagingSenderId: '461278347881',
    projectId: 'pumba-project-3b8bb',
    storageBucket: 'pumba-project-3b8bb.firebasestorage.app',
    iosBundleId: 'com.example.pumbaProject',
  );
}
